<template>
  <div class="bg-gradient-to-r from-blue-200 via-purple-200 to-pink-200 min-h-screen p-6">
        <Head>
      <Title>M3ROUF Influencers</Title>
    </Head>
    <div class="flex flex-col gap-5 mt-10 text-center align-middle">
      <img class="h-28 w-28 rounded-full mx-auto" src="assets/images/logo.png" alt="" />
      <h2 class="font-bold text-2xl font-mono">M3ROUF Influencers</h2>
    </div>

    <div
      class="px-4 md:px-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 mt-10"
    >
      <div
        v-for="(influencer, index) in influencers"
        :key="index"
        class="influencer-card"
      >
        <div class="flex flex-row gap-6">
          <img :src="influencer.Photo || 'default-photo.png'" alt="" />
          <h3 class="font-semibold">{{ influencer.Name }}</h3>
        </div>
        <div class="mt-4 flex flex-row justify-around align-middle">
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.Insagram"
          >
            <Icon name="skill-icons:instagram" class="my-auto" />
            {{ influencer.Insagram }}
          </p>
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.facebook"
          >
            <Icon name="logos:facebook" class="my-auto" /> {{ influencer.facebook }}
          </p>
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.Youtube"
          >
            <Icon name="logos:youtube-icon" class="my-auto" /> {{ influencer.Youtube }}
          </p>
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.tiktok"
          >
            <Icon name="logos:tiktok-icon" class="my-auto" /> {{ influencer.tiktok }}
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const influencers = ref([
  {
    UserName: "_wardshah",
    Insagram: "1.1M",
    facebook: null,
    Youtube: null,
    tiktok: "12k",
    Name: "wardshah",
    Photo: null,
  },
  {
    UserName: "3omadd",
    Insagram: "73.4k",
    facebook: null,
    Youtube: null,
    tiktok: "133k",
    Name: "Ahmed Emad",
    Photo: null,
  },
  {
    UserName: "abdallahesmail_20",
    Insagram: "2k",
    facebook: null,
    Youtube: null,
    tiktok: "5.2k",
    Name: "abdallah Esmail",
    Photo: null,
  },
  {
    UserName: "9li9",
    Insagram: "1.4M",
    facebook: "2.7M",
    Youtube: "1.5M",
    tiktok: "559k",
    Name: "Abdulrhman mosad",
    Photo: null,
  },
  {
    UserName: "abdallaanabil",
    Insagram: "152k",
    facebook: null,
    Youtube: null,
    tiktok: "376.5K",
    Name: "Abdalla Nabil",
    Photo: null,
  },
  {
    UserName: "a_s_m_r_e_k_a_ph",
    Insagram: "103k",
    facebook: null,
    Youtube: null,
    tiktok: "976.3k",
    Name: "Asmarekah",
    Photo: null,
  },
  {
    UserName: "1mennawaleed",
    Insagram: "51.7K",
    facebook: null,
    Youtube: null,
    tiktok: "5.5k",
    Name: "Menna waleed",
    Photo: null,
  },
  {
    UserName: "adhamsamehh1",
    Insagram: "52.8K",
    facebook: "27K",
    Youtube: null,
    tiktok: "136.3K",
    Name: "Adham Sameh",
    Photo: null,
  },
  {
    UserName: "ahmed_kamal_06",
    Insagram: "1M",
    facebook: null,
    Youtube: null,
    tiktok: "6.2M",
    Name: "Ahmed Kamel",
    Photo: null,
  },
  {
    UserName: "ahmedcooty",
    Insagram: "713K",
    facebook: "73K",
    Youtube: null,
    tiktok: "304.4K",
    Name: "Ahmed Cooty",
    Photo: null,
  },
  {
    UserName: "ahmed_hany_rashdan",
    Insagram: "304K",
    facebook: null,
    Youtube: null,
    tiktok: "773.9K",
    Name: "Ahmed Hany",
    Photo: null,
  },
  {
    UserName: "ahmed_sami_phg",
    Insagram: "235K",
    facebook: null,
    Youtube: null,
    tiktok: "31.6K",
    Name: "Ahmed Sami",
    Photo: null,
  },
  {
    UserName: "ahmedeisaofficial",
    Insagram: "157K",
    facebook: null,
    Youtube: null,
    tiktok: "95.7K",
    Name: "Ahmed Eisa",
    Photo: null,
  },
  {
    UserName: "ahmed_hisham_banknote",
    Insagram: "194K",
    facebook: null,
    Youtube: null,
    tiktok: "742.5K",
    Name: "Ahmed Hisham",
    Photo: null,
  },
  {
    UserName: "ahmedellsaeed",
    Insagram: "256K",
    facebook: null,
    Youtube: "800K",
    tiktok: "160.2K",
    Name: "Ahmed El Saeed",
    Photo: null,
  },
  {
    UserName: "abdalla.ibrahim.alameldin",
    Insagram: "42.3K",
    facebook: "22K",
    Youtube: null,
    tiktok: "2.9k",
    Name: "Abdalla ibrahim",
    Photo: null,
  },
  {
    UserName: "ahmedgamal.official",
    Insagram: "1M",
    facebook: "1.4M ",
    Youtube: null,
    tiktok: null,
    Name: "Ahmed Gamal",
    Photo: null,
  },
  {
    UserName: "ahmed.keshk.official",
    Insagram: "152k",
    facebook: null,
    Youtube: null,
    tiktok: "68.6k",
    Name: "Ahmed keshk",
    Photo: null,
  },
  {
    UserName: "ahmed_alkial",
    Insagram: "145k",
    facebook: "71K",
    Youtube: null,
    tiktok: "1.2M",
    Name: "Ahmed Alkial",
    Photo: null,
  },
  {
    UserName: "habibaismail",
    Insagram: "81.3K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "habiba ismail",
    Photo: null,
  },
  {
    UserName: "_chefm",
    Insagram: "1.6M",
    facebook: null,
    Youtube: null,
    tiktok: "184.4K",
    Name: "Mohamed Hamed",
    Photo: null,
  },
  {
    UserName: "ahmedel_shahat",
    Insagram: "157K",
    facebook: null,
    Youtube: null,
    tiktok: "63K",
    Name: "Ahmed Elshahat",
    Photo: null,
  },
  {
    UserName: "alidoniaofficial",
    Insagram: "1M",
    facebook: null,
    Youtube: null,
    tiktok: "1.1M",
    Name: "Ali Donia",
    Photo: null,
  },
  {
    UserName: "alaakassem25",
    Insagram: "510K",
    facebook: null,
    Youtube: null,
    tiktok: "13k",
    Name: "Alaa Kassem",
    Photo: null,
  },
  {
    UserName: "amar_ashraf_official",
    Insagram: "344K",
    facebook: "3.5M",
    Youtube: "665k",
    tiktok: "6.3M",
    Name: "Ammar Ashraf",
    Photo: null,
  },
  {
    UserName: "amiraaboalnaga",
    Insagram: "64.6K",
    facebook: null,
    Youtube: null,
    tiktok: "8k",
    Name: "Amira Aboalnaga",
    Photo: null,
  },
  {
    UserName: "aligaber_fox",
    Insagram: "20.2K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Ali Gaber",
    Photo: null,
  },
  {
    UserName: "amira.sayyed",
    Insagram: "539K",
    facebook: null,
    Youtube: null,
    tiktok: "23.5K",
    Name: "Amira Sayed",
    Photo: null,
  },
  {
    UserName: "amr_elwadidy",
    Insagram: "114K",
    facebook: null,
    Youtube: null,
    tiktok: "19.1k",
    Name: "Amr elwadidy",
    Photo: null,
  },
  {
    UserName: "amlyouness",
    Insagram: "43.9K",
    facebook: null,
    Youtube: "6.4k",
    tiktok: "13.8K",
    Name: "Aml Youness",
    Photo: null,
  },
  {
    UserName: "amlabdelmaboud",
    Insagram: "199K",
    facebook: null,
    Youtube: null,
    tiktok: "8k",
    Name: "Aml Abdelmaboud",
    Photo: null,
  },
  {
    UserName: "amiragamal.official",
    Insagram: "142K",
    facebook: "676K",
    Youtube: null,
    tiktok: null,
    Name: "Amira Gamal",
    Photo: null,
  },
  {
    UserName: "amlhammadofficial",
    Insagram: "143K",
    facebook: null,
    Youtube: null,
    tiktok: "569.2K",
    Name: "Aml Hammad",
    Photo: null,
  },
  {
    UserName: "~Abdellrahman Ramadan",
    Insagram: "470K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Abdellrahman ramadan",
    Photo: null,
  },
  {
    UserName: "aliaadarwich_makeupartist",
    Insagram: "239K",
    facebook: null,
    Youtube: null,
    tiktok: "7.1k",
    Name: "Aliaa Darwish",
    Photo: null,
  },
  {
    UserName: "amiraelhelw_",
    Insagram: "152K",
    facebook: null,
    Youtube: null,
    tiktok: "78.7K",
    Name: "Amira\u2002Elhelw",
    Photo: null,
  },
  {
    UserName: "amiraaloqda",
    Insagram: "100K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Amira Aloqda",
    Photo: null,
  },
  {
    UserName: "ahmedimamofficial",
    Insagram: "142K",
    facebook: "431K",
    Youtube: null,
    tiktok: null,
    Name: "Ahmed Ashmawy",
    Photo: null,
  },
  {
    UserName: "mazenghareb3",
    Insagram: "273K",
    facebook: "970k",
    Youtube: "31.7k",
    tiktok: "1.5M",
    Name: "Mazen Ghareb",
    Photo: null,
  },
  {
    UserName: "ahmeed.ts",
    Insagram: "390K ",
    facebook: null,
    Youtube: null,
    tiktok: "1.4M",
    Name: "Ahmed Ts",
    Photo: null,
  },
  {
    UserName: "ahmedrafat25",
    Insagram: "754K",
    facebook: "6.4M",
    Youtube: "6.4M",
    tiktok: "2.1M",
    Name: "Ahmed Raafat",
    Photo: null,
  },
  {
    UserName: "ahmeednassar",
    Insagram: "166K",
    facebook: null,
    Youtube: null,
    tiktok: "263.3K",
    Name: "Ahmed Nasser",
    Photo: null,
  },
  {
    UserName: "aida_s3id",
    Insagram: "295K",
    facebook: null,
    Youtube: null,
    tiktok: "231.4K",
    Name: "Aida said",
    Photo: null,
  },
  {
    UserName: "al_azzazy",
    Insagram: "516K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Maha El Azzazy",
    Photo: null,
  },
  {
    UserName: "alaa.mamdou7",
    Insagram: "46K",
    facebook: null,
    Youtube: null,
    tiktok: "16.2K",
    Name: "Alaa Mamdouh",
    Photo: null,
  },
  {
    UserName: "~Ammer Taher",
    Insagram: "473K",
    facebook: "59K",
    Youtube: null,
    tiktok: "36.2K",
    Name: "Ammer Taher",
    Photo: null,
  },
  {
    UserName: "alaa_rayan111",
    Insagram: "100K",
    facebook: null,
    Youtube: null,
    tiktok: "25.6K",
    Name: "Alaa rayan",
    Photo: null,
  },
  {
    UserName: "ahmednasser_15",
    Insagram: "21.6K ",
    facebook: null,
    Youtube: null,
    tiktok: "31.8K",
    Name: "Ahmed Nasser",
    Photo: null,
  },
  {
    UserName: "ahmedyouniis",
    Insagram: "366K",
    facebook: null,
    Youtube: null,
    tiktok: "968.4K",
    Name: "Ahmed Younis ",
    Photo: null,
  },
  {
    UserName: "alaa.el_hosien",
    Insagram: "124K",
    facebook: null,
    Youtube: null,
    tiktok: "2.2k",
    Name: "Alaa El-hosien",
    Photo: null,
  },
  {
    UserName: "ahmedlotfy101",
    Insagram: "1.3M",
    facebook: "173K",
    Youtube: null,
    tiktok: "1.2M",
    Name: "Ahmed Lotfy",
    Photo: null,
  },
  {
    UserName: "alaa_elboushy",
    Insagram: "260K",
    facebook: null,
    Youtube: null,
    tiktok: "36.6K",
    Name: "Alaa Elboushy",
    Photo: null,
  },
  {
    UserName: "ahmedmohsen.22",
    Insagram: "466K",
    facebook: null,
    Youtube: null,
    tiktok: "909K",
    Name: "Ahmed Mohsen",
    Photo: null,
  },
  {
    UserName: "amr_ismat",
    Insagram: "197K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Amr Ismat",
    Photo: null,
  },
  {
    UserName: "amroelmeligy",
    Insagram: "137K",
    facebook: "31K",
    Youtube: null,
    tiktok: "2.2k",
    Name: "Amro El Meligy",
    Photo: null,
  },
  {
    UserName: "arahmanmagdy",
    Insagram: "223K",
    facebook: null,
    Youtube: "77.3k",
    tiktok: "192.6K",
    Name: "AbdulRahman Magdy",
    Photo: null,
  },
  {
    UserName: "areejkassem23",
    Insagram: "444K",
    facebook: null,
    Youtube: null,
    tiktok: "110.6K",
    Name: "Areej kassem",
    Photo: null,
  },
  {
    UserName: "amrgabergadallah",
    Insagram: "1.2M",
    facebook: null,
    Youtube: null,
    tiktok: "386.9K",
    Name: "Amr Gaber",
    Photo: null,
  },
  {
    UserName: "amromamdouhperformance",
    Insagram: "141K",
    facebook: null,
    Youtube: null,
    tiktok: "499.2K",
    Name: "Amro Mamdouh",
    Photo: null,
  },
  {
    UserName: "arwaellaithy",
    Insagram: "65.1K",
    facebook: null,
    Youtube: null,
    tiktok: "30.8K",
    Name: "Arwa Elaithi",
    Photo: null,
  },
  {
    UserName: "amrbadawy_",
    Insagram: "122K",
    facebook: "728K ",
    Youtube: null,
    tiktok: null,
    Name: "Amr Badawy ",
    Photo: null,
  },
  {
    UserName: "ayaessam117",
    Insagram: "1.6M",
    facebook: null,
    Youtube: null,
    tiktok: "1.3M",
    Name: "Aya Essam",
    Photo: null,
  },
  {
    UserName: "Asma Oraby",
    Insagram: "166K ",
    facebook: null,
    Youtube: "4.4K",
    tiktok: "5.3k",
    Name: "Asma Oraby",
    Photo: null,
  },
  {
    UserName: "ayasokkar",
    Insagram: "883K",
    facebook: null,
    Youtube: null,
    tiktok: "353.7K",
    Name: "Aya Sokkar",
    Photo: null,
  },
  {
    UserName: "basemelabd",
    Insagram: "392K",
    facebook: null,
    Youtube: null,
    tiktok: "527.4K",
    Name: "Basem Elabd",
    Photo: null,
  },
  {
    UserName: "basemofficial_",
    Insagram: "193K ",
    facebook: null,
    Youtube: null,
    tiktok: "2.3k",
    Name: "Basem Abd Alhafez",
    Photo: null,
  },
  {
    UserName: "bakr.magdy.official",
    Insagram: "155K",
    facebook: null,
    Youtube: "2.19k",
    tiktok: "2.7k",
    Name: "Bakr magdy",
    Photo: null,
  },
  {
    UserName: "ayatsaqrrrr",
    Insagram: "107K",
    facebook: "76K",
    Youtube: null,
    tiktok: "8.5k",
    Name: "Ayat Saqr",
    Photo: null,
  },
  {
    UserName: "ayatollah_hassan1",
    Insagram: "200K",
    facebook: null,
    Youtube: null,
    tiktok: "9.5k",
    Name: "Ayatollah Hassan",
    Photo: null,
  },
  {
    UserName: "bassmaayad_",
    Insagram: "109K",
    facebook: null,
    Youtube: null,
    tiktok: "75K",
    Name: "Bassma Ayad",
    Photo: null,
  },
  {
    UserName: "ben_tarekk",
    Insagram: "46.2K",
    facebook: null,
    Youtube: null,
    tiktok: "35K",
    Name: "Youssef Tarek",
    Photo: null,
  },
  {
    UserName: "amira_shalby252",
    Insagram: "1M",
    facebook: null,
    Youtube: null,
    tiktok: "121.7K",
    Name: "Amira Shalby",
    Photo: null,
  },
  {
    UserName: "azouzadel",
    Insagram: "219K ",
    facebook: "2.7M",
    Youtube: null,
    tiktok: "45.4K",
    Name: "Azouz Adel",
    Photo: null,
  },
  {
    UserName: "bassantmamdouh__",
    Insagram: "213K",
    facebook: "12K",
    Youtube: null,
    tiktok: "114K",
    Name: "Bassant Mamdouh",
    Photo: null,
  },
  {
    UserName: "alhusseinamr_7",
    Insagram: "74.7K",
    facebook: "48K",
    Youtube: null,
    tiktok: "10k",
    Name: "Alhussein Amr",
    Photo: null,
  },
  {
    UserName: "boshy_official",
    Insagram: "139K",
    facebook: null,
    Youtube: "97.2k",
    tiktok: null,
    Name: "Ahmed khaled",
    Photo: null,
  },
  {
    UserName: "babyjessy",
    Insagram: "152K",
    facebook: null,
    Youtube: null,
    tiktok: "100.3K",
    Name: "Jasmin",
    Photo: null,
  },
  {
    UserName: "baherra_",
    Insagram: "530K",
    facebook: null,
    Youtube: null,
    tiktok: "1.7M",
    Name: "Bahera montasir",
    Photo: null,
  },
  {
    UserName: "ahmedkabokabo",
    Insagram: "72K",
    facebook: null,
    Youtube: null,
    tiktok: "3M",
    Name: "Ahmed Ashraf",
    Photo: null,
  },
  {
    UserName: "bahaaelkhateebofficial",
    Insagram: "183K ",
    facebook: null,
    Youtube: null,
    tiktok: "1.5k",
    Name: "Bahaa Eldin Elkhateeb",
    Photo: null,
  },
  {
    UserName: "asmaa_essam_makeup_artist",
    Insagram: "170K",
    facebook: null,
    Youtube: null,
    tiktok: "1.1k",
    Name: "Asmaa Essam",
    Photo: null,
  },
  {
    UserName: "asmaali_official",
    Insagram: "111K",
    facebook: null,
    Youtube: null,
    tiktok: "154.6K",
    Name: "Asmaa Ali",
    Photo: null,
  },
]);
</script>

<style scoped>
.influencer-card {
  border: 1px solid #ccc;
  padding: 20px;
  border-radius: 15px;
  transition: all 0.3s ease-in-out;
}

.influencer-card:hover {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);
  transform: scale(1.05);
  background: linear-gradient(to right, #e0f7fa, #f3e5f5);
}
</style>
