<template>
<div class="bg-gradient-to-r from-yellow-300 via-yellow-500 to-yellow-700 min-h-screen p-6">

        <Head>
      <Title>M3ROUF Influencers</Title>
    </Head>
    <div class="flex flex-col gap-5 mt-10 text-center align-middle">
      <img class="h-28 w-28 rounded-full mx-auto" src="assets/images/logo.png" alt="" />
      <h2 class="font-bold text-2xl font-mono">M3ROUF Influencers</h2>
    </div>

    <div
      class="px-4 md:px-20 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10 mt-10"
    >
      <div
        v-for="(influencer, index) in influencers"
        :key="index"
        class="influencer-card"
      >
        <div class="flex flex-row  gap-6">
      <img class="h-20 w-20 rounded-full" v-if="influencer.Photo" :src="influencer.Photo" :alt="influencer.Name" />
          <h3 class="font-semibold my-auto">{{ influencer.Name }}</h3>
        </div>
        <div class="mt-4 flex flex-row justify-around align-middle">
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.Insagram"
          >
            <Icon name="skill-icons:instagram" class="my-auto" />
            {{ influencer.Insagram }}
          </p>
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.facebook"
          >
            <Icon name="logos:facebook" class="my-auto" /> {{ influencer.facebook }}
          </p>
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.Youtube"
          >
            <Icon name="logos:youtube-icon" class="my-auto" /> {{ influencer.Youtube }}
          </p>
          <p
            class="flex flex-row gap-2 align-middle justify-center font-medium"
            v-if="influencer.tiktok"
          >
            <Icon name="logos:tiktok-icon" class="my-auto" /> {{ influencer.tiktok }}
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const influencers = ref([
  {
    UserName: "_wardshah",
    Insagram: "1.1M",
    facebook: null,
    Youtube: null,
    tiktok: "12k",
    Name: "wardshah",
    Photo: "https://i.postimg.cc/Nfvhqbhg/wardshah.png",
  },
  {
    UserName: "3omadd",
    Insagram: "73.4k",
    facebook: null,
    Youtube: null,
    tiktok: "133k",
    Name: "Ahmed Emad",
    Photo: "https://i.postimg.cc/L68XfHXY/Ahmed-Emad.png",
  },

  {
    UserName: "9li9",
    Insagram: "1.4M",
    facebook: "2.7M",
    Youtube: "1.5M",
    tiktok: "559k",
    Name: "Abdulrhman mosad",
    Photo: "https://i.postimg.cc/vTz4yTmM/Abdulrhman-mosad.png",
  },
  {
    UserName: "abdallaanabil",
    Insagram: "152k",
    facebook: null,
    Youtube: null,
    tiktok: "376.5K",
    Name: "Abdalla Nabil",
    Photo: "https://i.postimg.cc/Dz9JdRDV/Abdalla-Nabil.png",
  },
  {
    UserName: "a_s_m_r_e_k_a_ph",
    Insagram: "103k",
    facebook: null,
    Youtube: null,
    tiktok: "976.3k",
    Name: "Asmarekah",
    Photo: "https://i.postimg.cc/JzC2vhkt/Asmarekah.png",
  },
  {
    UserName: "1mennawaleed",
    Insagram: "51.7K",
    facebook: null,
    Youtube: null,
    tiktok: "5.5k",
    Name: "Menna waleed",
    Photo: "https://i.postimg.cc/C5DWnn8T/Menna_waleed.png",
  },
  {
    UserName: "adhamsamehh1",
    Insagram: "52.8K",
    facebook: "27K",
    Youtube: null,
    tiktok: "136.3K",
    Name: "Adham Sameh",
    Photo: "https://i.postimg.cc/qM1NZNYx/Adham-Sameh.png",
  },
  {
    UserName: "ahmed_kamal_06",
    Insagram: "1M",
    facebook: null,
    Youtube: null,
    tiktok: "6.2M",
    Name: "Ahmed Kamel",
    Photo: "https://i.postimg.cc/kXY5vk6j/Ahmed-Kamel.png",
  },
  {
    UserName: "ahmedcooty",
    Insagram: "713K",
    facebook: "73K",
    Youtube: null,
    tiktok: "304.4K",
    Name: "Ahmed Cooty",
    Photo: "https://i.postimg.cc/NjV5BWQy/Ahmed-Cooty.png",
  },
  {
    UserName: "ahmed_hany_rashdan",
    Insagram: "304K",
    facebook: null,
    Youtube: null,
    tiktok: "773.9K",
    Name: "Ahmed Hany",
    Photo: "https://i.postimg.cc/prqL7S0L/Ahmed-Hany.png",
  },
  {
    UserName: "ahmed_sami_phg",
    Insagram: "235K",
    facebook: null,
    Youtube: null,
    tiktok: "31.6K",
    Name: "Ahmed Sami",
    Photo: "https://i.postimg.cc/v838GpzQ/Ahmed-Sami.png",
  },
  {
    UserName: "ahmedeisaofficial",
    Insagram: "157K",
    facebook: null,
    Youtube: null,
    tiktok: "95.7K",
    Name: "Ahmed Eisa",
    Photo: "https://i.postimg.cc/rm2stx0M/Ahmed-Eisa.png",
  },
  {
    UserName: "ahmed_hisham_banknote",
    Insagram: "194K",
    facebook: null,
    Youtube: null,
    tiktok: "742.5K",
    Name: "Ahmed Hisham",
    Photo: "https://i.postimg.cc/445ymKJR/Ahmed-Hisham.png",
  },
  {
    UserName: "ahmedellsaeed",
    Insagram: "256K",
    facebook: null,
    Youtube: "800K",
    tiktok: "160.2K",
    Name: "Ahmed El Saeed",
    Photo: "https://i.postimg.cc/0NwrQcNV/Ahmed-El-Saeed.png",
  },
  {
    UserName: "abdalla.ibrahim.alameldin",
    Insagram: "42.3K",
    facebook: "22K",
    Youtube: null,
    tiktok: "2.9k",
    Name: "Abdalla ibrahim",
    Photo: "https://i.postimg.cc/yNg3R7LX/Abdalla-ibrahim.png",
  },
  {
    UserName: "ahmedgamal.official",
    Insagram: "1M",
    facebook: "1.4M ",
    Youtube: null,
    tiktok: null,
    Name: "Ahmed Gamal",
    Photo: "https://i.postimg.cc/XqVvsWkP/Ahmed-Gamal.png",
  },
  {
    UserName: "ahmed.keshk.official",
    Insagram: "152k",
    facebook: null,
    Youtube: null,
    tiktok: "68.6k",
    Name: "Ahmed keshk",
    Photo: "https://i.postimg.cc/XYT7Tdgd/Ahmed-keshk.png",
  },
  {
    UserName: "ahmed_alkial",
    Insagram: "145k",
    facebook: "71K",
    Youtube: null,
    tiktok: "1.2M",
    Name: "Ahmed Alkial",
    Photo: "https://i.postimg.cc/9QzD3WH5/Ahmed-Alkial.png",
  },
  {
    UserName: "habibaismail",
    Insagram: "81.3K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "habiba ismail",
    Photo: "https://i.postimg.cc/bvwcVv7k/habiba_ismail.png",
  },
  {
    UserName: "_chefm",
    Insagram: "1.6M",
    facebook: null,
    Youtube: null,
    tiktok: "184.4K",
    Name: "Mohamed Hamed",
    Photo: "https://i.postimg.cc/66vsmgmj/Mohamed_Hamed.png",
  },
  {
    UserName: "ahmedel_shahat",
    Insagram: "157K",
    facebook: null,
    Youtube: null,
    tiktok: "63K",
    Name: "Ahmed Elshahat",
    Photo: "https://i.postimg.cc/RF1F1hKf/Ahmed-Elshahat.png",
  },
  {
    UserName: "alidoniaofficial",
    Insagram: "1M",
    facebook: null,
    Youtube: null,
    tiktok: "1.1M",
    Name: "Ali Donia",
    Photo: "https://i.postimg.cc/gjTP3bS8/Ali-Donia.png",
  },
  {
    UserName: "alaakassem25",
    Insagram: "510K",
    facebook: null,
    Youtube: null,
    tiktok: "13k",
    Name: "Alaa Kassem",
    Photo: "https://i.postimg.cc/C1J0Lqbv/Alaa-Kassem.png",
  },
  {
    UserName: "amar_ashraf_official",
    Insagram: "344K",
    facebook: "3.5M",
    Youtube: "665k",
    tiktok: "6.3M",
    Name: "Ammar Ashraf",
    Photo: "https://i.postimg.cc/rw5vw4kS/Ammar-Ashraf.png",
  },
  {
    UserName: "amiraaboalnaga",
    Insagram: "64.6K",
    facebook: null,
    Youtube: null,
    tiktok: "8k",
    Name: "Amira Aboalnaga",
    Photo: "https://i.postimg.cc/dtgY1vTK/Amira-Aboalnaga.png",
  },
  {
    UserName: "aligaber_fox",
    Insagram: "20.2K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Ali Gaber",
    Photo: "https://i.postimg.cc/wxfzCDqM/Ali-Gaber.png",
  },
  {
    UserName: "amira.sayyed",
    Insagram: "539K",
    facebook: null,
    Youtube: null,
    tiktok: "23.5K",
    Name: "Amira Sayed",
    Photo: "https://i.postimg.cc/PqQs2wVt/Amira-Sayed.png",
  },
  {
    UserName: "amr_elwadidy",
    Insagram: "114K",
    facebook: null,
    Youtube: null,
    tiktok: "19.1k",
    Name: "Amr elwadidy",
    Photo: "https://i.postimg.cc/Xv3tGvjt/Amr_elwadidy.png",
  },
  {
    UserName: "amlyouness",
    Insagram: "43.9K",
    facebook: null,
    Youtube: "6.4k",
    tiktok: "13.8K",
    Name: "Aml Youness",
    Photo: "https://i.postimg.cc/qB5fb0wC/Aml-Youness.png",
  },
  {
    UserName: "amlabdelmaboud",
    Insagram: "199K",
    facebook: null,
    Youtube: null,
    tiktok: "8k",
    Name: "Aml Abdelmaboud",
    Photo: "https://i.postimg.cc/0jrTkHkQ/Aml-Abdelmaboud.png",
  },
  {
    UserName: "amiragamal.official",
    Insagram: "142K",
    facebook: "676K",
    Youtube: null,
    tiktok: null,
    Name: "Amira Gamal",
    Photo: "https://i.postimg.cc/jjbYHXXg/Amira-Gamal.png",
  },
  {
    UserName: "amlhammadofficial",
    Insagram: "143K",
    facebook: null,
    Youtube: null,
    tiktok: "569.2K",
    Name: "Aml Hammad",
    Photo: "https://i.postimg.cc/hvwHfbv0/Aml-Hammad.png",
  },
  {
    UserName: "~Abdellrahman Ramadan",
    Insagram: "470K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Abdellrahman ramadan",
    Photo: "https://i.postimg.cc/kG92LKqf/Abdellrahman-ramadan.png",
  },
  {
    UserName: "aliaadarwich_makeupartist",
    Insagram: "239K",
    facebook: null,
    Youtube: null,
    tiktok: "7.1k",
    Name: "Aliaa Darwish",
    Photo: "https://i.postimg.cc/gkxpmrjD/Aliaa-Darwish.png",
  },
  {
    UserName: "amiraelhelw_",
    Insagram: "152K",
    facebook: null,
    Youtube: null,
    tiktok: "78.7K",
    Name: "Amira\u2002Elhelw",
    Photo: "https://i.postimg.cc/mDdxGGGJ/Amira-Elhelw.png",
  },
  {
    UserName: "amiraaloqda",
    Insagram: "100K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Amira Aloqda",
    Photo: "https://i.postimg.cc/qvnd6Y86/Amira-Aloqda.png",
  },
  {
    UserName: "ahmedimamofficial",
    Insagram: "142K",
    facebook: "431K",
    Youtube: null,
    tiktok: null,
    Name: "Ahmed Ashmawy",
    Photo: "https://i.postimg.cc/05dMDW03/Ahmed-Ashmawy.png",
  },
  {
    UserName: "mazenghareb3",
    Insagram: "273K",
    facebook: "970k",
    Youtube: "31.7k",
    tiktok: "1.5M",
    Name: "Mazen Ghareb",
    Photo: "https://i.postimg.cc/nzNyLGCG/Mazen_Ghareb.png",
  },
  {
    UserName: "ahmeed.ts",
    Insagram: "390K ",
    facebook: null,
    Youtube: null,
    tiktok: "1.4M",
    Name: "Ahmed Ts",
    Photo: "https://i.postimg.cc/Gt7bzy2B/Ahmed-Ts.png",
  },
  {
    UserName: "ahmedrafat25",
    Insagram: "754K",
    facebook: "6.4M",
    Youtube: "6.4M",
    tiktok: "2.1M",
    Name: "Ahmed Raafat",
    Photo: "https://i.postimg.cc/sxDVpcVd/Ahmed-Raafat.png",
  },
  {
    UserName: "ahmeednassar",
    Insagram: "166K",
    facebook: null,
    Youtube: null,
    tiktok: "263.3K",
    Name: "Ahmed Nasser",
    Photo: "https://i.postimg.cc/4d1f7MRQ/Ahmed-Nasser.png",
  },
  {
    UserName: "aida_s3id",
    Insagram: "295K",
    facebook: null,
    Youtube: null,
    tiktok: "231.4K",
    Name: "Aida said",
    Photo: "https://i.postimg.cc/kXHnbKzz/Aida-said.png",
  },
  {
    UserName: "al_azzazy",
    Insagram: "516K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Maha El Azzazy",
    Photo: "https://i.postimg.cc/hjJFg5PG/Maha_El_Azzazy.png",
  },
  {
    UserName: "alaa.mamdou7",
    Insagram: "46K",
    facebook: null,
    Youtube: null,
    tiktok: "16.2K",
    Name: "Alaa Mamdouh",
    Photo: "https://i.postimg.cc/MG7xN4HJ/Alaa-Mamdouh.png",
  },
  {
    UserName: "~Ammer Taher",
    Insagram: "473K",
    facebook: "59K",
    Youtube: null,
    tiktok: "36.2K",
    Name: "Ammer Taher",
    Photo: "https://i.postimg.cc/TYLzBSNN/Ammer-Taher.png",
  },
  {
    UserName: "alaa_rayan111",
    Insagram: "100K",
    facebook: null,
    Youtube: null,
    tiktok: "25.6K",
    Name: "Alaa rayan",
    Photo: "https://i.postimg.cc/V6z18R0r/Alaa-rayan.png",
  },
  {
    UserName: "ahmedyouniis",
    Insagram: "366K",
    facebook: null,
    Youtube: null,
    tiktok: "968.4K",
    Name: "Ahmed Younis ",
    Photo: "https://i.postimg.cc/ZKnbnV76/Ahmed-Younis.png",
  },
  {
    UserName: "alaa.el_hosien",
    Insagram: "124K",
    facebook: null,
    Youtube: null,
    tiktok: "2.2k",
    Name: "Alaa El-hosien",
    Photo: "https://i.postimg.cc/LsK2yRHV/Alaa-El-hosien.png",
  },
  {
    UserName: "ahmedlotfy101",
    Insagram: "1.3M",
    facebook: "173K",
    Youtube: null,
    tiktok: "1.2M",
    Name: "Ahmed Lotfy",
    Photo: "https://i.postimg.cc/6Qn5wqHS/Ahmed-Lotfy.png",
  },
  {
    UserName: "alaa_elboushy",
    Insagram: "260K",
    facebook: null,
    Youtube: null,
    tiktok: "36.6K",
    Name: "Alaa Elboushy",
    Photo: "https://i.postimg.cc/Sxzm7jps/Alaa-Elboushy.png",
  },
  {
    UserName: "ahmedmohsen.22",
    Insagram: "466K",
    facebook: null,
    Youtube: null,
    tiktok: "909K",
    Name: "Ahmed Mohsen",
    Photo: "https://i.postimg.cc/vBy8mykm/Ahmed-Mohsen.png",
  },
  {
    UserName: "amr_ismat",
    Insagram: "197K",
    facebook: null,
    Youtube: null,
    tiktok: null,
    Name: "Amr Ismat",
    Photo: "https://i.postimg.cc/wvjP2bsV/Amr_Ismat.png",
  },
  {
    UserName: "amroelmeligy",
    Insagram: "137K",
    facebook: "31K",
    Youtube: null,
    tiktok: "2.2k",
    Name: "Amro El Meligy",
    Photo: "https://i.postimg.cc/FRC6BgyQ/Amro_El_Meligy.png",
  },
  {
    UserName: "arahmanmagdy",
    Insagram: "223K",
    facebook: null,
    Youtube: "77.3k",
    tiktok: "192.6K",
    Name: "AbdulRahman Magdy",
    Photo: "https://i.postimg.cc/Y9Q4XbKv/Abdul-Rahman-Magdy.png",
  },
  {
    UserName: "areejkassem23",
    Insagram: "444K",
    facebook: null,
    Youtube: null,
    tiktok: "110.6K",
    Name: "Areej kassem",
    Photo: "https://i.postimg.cc/yxwbV1pQ/Areej_kassem.png",
  },
  {
    UserName: "amrgabergadallah",
    Insagram: "1.2M",
    facebook: null,
    Youtube: null,
    tiktok: "386.9K",
    Name: "Amr Gaber",
    Photo: "https://i.postimg.cc/435qzTny/Amr_Gaber.png",
  },
  {
    UserName: "amromamdouhperformance",
    Insagram: "141K",
    facebook: null,
    Youtube: null,
    tiktok: "499.2K",
    Name: "Amro Mamdouh",
    Photo: "https://i.postimg.cc/fy3PntCS/Amro_Mamdouh.png",
  },
  {
    UserName: "arwaellaithy",
    Insagram: "65.1K",
    facebook: null,
    Youtube: null,
    tiktok: "30.8K",
    Name: "Arwa Elaithi",
    Photo: "https://i.postimg.cc/sf88PmfY/Arwa_Elaithi.png",
  },
  {
    UserName: "amrbadawy_",
    Insagram: "122K",
    facebook: "728K ",
    Youtube: null,
    tiktok: null,
    Name: "Amr Badawy ",
    Photo: "https://i.postimg.cc/Kv66bNdG/Amr_Badawy.png",
  },
  {
    UserName: "ayaessam117",
    Insagram: "1.6M",
    facebook: null,
    Youtube: null,
    tiktok: "1.3M",
    Name: "Aya Essam",
    Photo: "https://i.postimg.cc/x1G42Sv5/Aya_Essam.png",
  },
  {
    UserName: "Asma Oraby",
    Insagram: "166K ",
    facebook: null,
    Youtube: "4.4K",
    tiktok: "5.3k",
    Name: "Asma Oraby",
    Photo: "https://i.postimg.cc/ZKdQwN01/Asma_Oraby.png",
  },
  {
    UserName: "ayasokkar",
    Insagram: "883K",
    facebook: null,
    Youtube: null,
    tiktok: "353.7K",
    Name: "Aya Sokkar",
    Photo: "https://i.postimg.cc/hGS343MB/Aya_Sokkar.png",
  },
  {
    UserName: "basemelabd",
    Insagram: "392K",
    facebook: null,
    Youtube: null,
    tiktok: "527.4K",
    Name: "Basem Elabd",
    Photo: "https://i.postimg.cc/8PLSj9dJ/Basem_Elabd.png",
  },
  {
    UserName: "basemofficial_",
    Insagram: "193K ",
    facebook: null,
    Youtube: null,
    tiktok: "2.3k",
    Name: "Basem Abd Alhafez",
    Photo: "https://i.postimg.cc/NG3tGBXv/Basem_Abd_Alhafez.png",
  },
  {
    UserName: "bakr.magdy.official",
    Insagram: "155K",
    facebook: null,
    Youtube: "2.19k",
    tiktok: "2.7k",
    Name: "Bakr magdy",
    Photo: "https://i.postimg.cc/XNG30ppg/Bakr_magdy.png",
  },
  {
    UserName: "ayatsaqrrrr",
    Insagram: "107K",
    facebook: "76K",
    Youtube: null,
    tiktok: "8.5k",
    Name: "Ayat Saqr",
    Photo: "https://i.postimg.cc/RFhsK6jp/Ayat_Saqr.png",
  },
  {
    UserName: "ayatollah_hassan1",
    Insagram: "200K",
    facebook: null,
    Youtube: null,
    tiktok: "9.5k",
    Name: "Ayatollah Hassan",
    Photo: "https://i.postimg.cc/DzBpSdYb/Ayatollah_Hassan.png",
  },
  {
    UserName: "bassmaayad_",
    Insagram: "109K",
    facebook: null,
    Youtube: null,
    tiktok: "75K",
    Name: "Bassma Ayad",
    Photo: "https://i.postimg.cc/13H1KFjy/Bassma_Ayad.png",
  },
  {
    UserName: "ben_tarekk",
    Insagram: "46.2K",
    facebook: null,
    Youtube: null,
    tiktok: "35K",
    Name: "Youssef Tarek",
    Photo: "https://i.postimg.cc/rF1B8Wc5/Youssef_Tarek.png",
  },
  {
    UserName: "amira_shalby252",
    Insagram: "1M",
    facebook: null,
    Youtube: null,
    tiktok: "121.7K",
    Name: "Amira Shalby",
    Photo: "https://i.postimg.cc/V6syTk2X/Amira-Shalby.png",
  },
  {
    UserName: "azouzadel",
    Insagram: "219K ",
    facebook: "2.7M",
    Youtube: null,
    tiktok: "45.4K",
    Name: "Azouz Adel",
    Photo: "https://i.postimg.cc/B6zhgZ3S/Azouz_Adel.png",
  },
  {
    UserName: "bassantmamdouh__",
    Insagram: "213K",
    facebook: "12K",
    Youtube: null,
    tiktok: "114K",
    Name: "Bassant Mamdouh",
    Photo: "https://i.postimg.cc/g2dPRs4M/Bassant_Mamdouh.png",
  },
  {
    UserName: "alhusseinamr_7",
    Insagram: "74.7K",
    facebook: "48K",
    Youtube: null,
    tiktok: "10k",
    Name: "Alhussein Amr",
    Photo: "https://i.postimg.cc/ZnRS95cJ/Alhussein-Amr.png",
  },
  {
    UserName: "boshy_official",
    Insagram: "139K",
    facebook: null,
    Youtube: "97.2k",
    tiktok: null,
    Name: "Ahmed khaled",
    Photo: "https://i.postimg.cc/vZ1Zq35G/Ahmed-khaled.png",
  },
  {
    UserName: "babyjessy",
    Insagram: "152K",
    facebook: null,
    Youtube: null,
    tiktok: "100.3K",
    Name: "Jasmin",
    Photo: "https://i.postimg.cc/5tKchVJG/Jasmin.png",
  },
  {
    UserName: "baherra_",
    Insagram: "530K",
    facebook: null,
    Youtube: null,
    tiktok: "1.7M",
    Name: "Bahera montasir",
    Photo: "https://i.postimg.cc/bdc376d4/Bahera_montasir.png",
  },
  {
    UserName: "ahmedkabokabo",
    Insagram: "72K",
    facebook: null,
    Youtube: null,
    tiktok: "3M",
    Name: "Ahmed Ashraf",
    Photo: "https://i.postimg.cc/X7jZ8f2v/Ahmed-Ashraf.png",
  },
  {
    UserName: "bahaaelkhateebofficial",
    Insagram: "183K ",
    facebook: null,
    Youtube: null,
    tiktok: "1.5k",
    Name: "Bahaa Eldin Elkhateeb",
    Photo: "https://i.postimg.cc/QCWfnLNp/Bahaa_Eldin_Elkhateeb.png",
  }
]);
</script>

<style scoped>
.influencer-card {
  border: 1px solid #ccc;
  padding: 20px;
  border-radius: 15px;
  transition: all 0.3s ease-in-out;
}

.influencer-card:hover {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);
  transform: scale(1.05);
  background: linear-gradient(to right, #e0f7fa, #f3e5f5);
}
</style>
